name: Build and test gallery-dl on macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout gallery-dl
        uses: actions/checkout@v4
        with:
          repository: mikf/gallery-dl
          ref: v1.29.7

      - name: Set up virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install .

      - name: Test gallery-dl version
        run: |
          source venv/bin/activate
          venv/bin/gallery-dl --version

      - name: Test with Instagram profile
        run: |
          source venv/bin/activate
          venv/bin/gallery-dl https://instagram.com/shreyaghoshal

      - name: Upload gallery-dl script
        uses: actions/upload-artifact@v4
        with:
          name: gallery-dl-macos-script
          path: venv/bin/gallery-dl
