name: Build gallery-dl from source (macOS)

on:
  workflow_dispatch:

jobs:
  build-from-source:
    runs-on: macos-latest

    steps:
      - name: Clone gallery-dl repo at tag v1.29.7
        uses: actions/checkout@v4
        with:
          repository: mikf/gallery-dl
          ref: v1.29.7

      - name: Set up Python environment (user-safe)
        run: |
          python3 -m pip install --upgrade --user pip setuptools wheel

      - name: Install gallery-dl locally
        run: |
          python3 -m pip install --user .

      - name: Run version check
        run: ~/.local/bin/gallery-dl --version

      - name: Run test scrape
        run: ~/.local/bin/gallery-dl https://instagram.com/shreyaghoshal

      - name: Copy binary for upload
        run: |
          mkdir -p dist
          cp ~/.local/bin/gallery-dl dist/gallery-dl

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: gallery-dl-built-macos
          path: dist/gallery-dl
