name: Build and Test gallery-dl on macOS

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout gallery-dl source
        uses: actions/checkout@v4
        with:
          repository: mikf/gallery-dl
          ref: v1.29.7

      - name: Set up Python and dependencies
        run: |
          brew install python
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install pyinstaller

      - name: Build standalone binary using PyInstaller
        run: |
          python3 -m PyInstaller --onefile --name gallery-dl __main__.py
          chmod +x dist/gallery-dl

      - name: Check binary version
        run: ./dist/gallery-dl --version

      - name: Run gallery-dl against Instagram profile
        run: ./dist/gallery-dl https://instagram.com/shreyaghoshal

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gallery-dl-macos
          path: dist/gallery-dl
